version: '3.8'

services:
  frontend:
    build:
      context: /opt/projects/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: frontend
    networks:
      - wanderlust-network

  backend:
    build:
      context: /opt/projects/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: backend
    depends_on:
      - mongo
    networks:
      - wanderlust-network

  mongo:
    build:
      context: /opt/projects/db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    container_name: mongodb
    networks:
      - wanderlust-network

networks:
  wanderlust-network:
    external: true

